---
# Official Ansible 2 way of gathering facts, regardless of --limit option
- hosts: controllers
  become: true
  pre_tasks:
    - name: Gathering facts from all controllers
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['controllers'] }}"
  tags: always

- name: Setup controllers
  hosts: controllers
  roles:
    - role: rabbitmq
      tags: rabbitmq
  become: True
