---

- name: Setup bootstrap vault
  hosts: bootstrap_vault
  roles:
    - { role: common, tags: common }
    - { role: bootstrap_vault, tags: bootstrap_vault }
  become: True

- name: Setup controllers
  hosts: controllers
  roles:
    - role: common
      tags: common
    - role: etcd
      tags: etcd
      vars:
        prefix: bootstrap-
        delegate_host: "{{ groups['bootstrap_vault'][0] }}"
    - role: vault
      tags: vault
  become: True
