---
- name: template {{ service_name }} configs
  template:
    src:  templates/{{ service_loop_item }}.j2
    dest: /opt/service/{{ service_name }}/{{ multi_service | ternary(service_binary + '/', '') }}{{ service_loop_item }}
  loop_control:
    loop_var: service_loop_item
  notify:
    - restart {{ service_name }} service
  with_items: "{{ service_templates }}"

- name: copy {{ service_name }} configs
  copy:
    src: files/{{ service_loop_item }}
    dest: /opt/service/{{ service_name }}/{{ multi_service | ternary(service_binary + '/', '') }}{{ service_loop_item }}
  loop_control:
    loop_var: service_loop_item
  notify:
    - restart {{ service_name }} service
  with_items: "{{ service_files }}"
