---

- include_role:
    name: certs
  with_items:
    - client
    - peer
    - server
  vars:
    prefix: "{{ cert_prefix | default('') }}"
    service: etcd
  loop_control:
    loop_var: ca_cert_type

- include_role:
    name: certs
  with_items:
    - client
    - peer
    - server
  vars:
    prefix: "{{ cert_prefix | default('') }}"
    service: etcd
  loop_control:
    loop_var: cert_type
