---

- import_tasks: generate_certs.yml
  when: generate_certs

- name: Ensure bootstrap-etcd certs directory exists
  file:
    state: directory
    path: /etc/certs/bootstrap-etcd/

- name: Write bootstrap-etcd {{ item }} ca
  copy:
    dest: /etc/certs/bootstrap-etcd/{{ item }}_ca.crt
    content: "{{ ansible_local.certs['bootstrap-etcd-' + item].ca }}"

- name: Write bootstrap-etcd {{ item }} cert
  copy:
    dest: /etc/certs/bootstrap-etcd/{{ item }}.crt
    content: "{{ ansible_local.certs['bootstrap-etcd-' + item].crt }}"

- name: Write bootstrap-etcd {{ item }} key
  copy:
    dest: /etc/certs/bootstrap-etcd/{{ item }}.key
    content: "{{ ansible_local.certs['bootstrap-etcd-' + item].key }}"
