---
- include_role:
    name: certs
  with_items:
    - client
    - peer
    - server
  vars:
    service: etcd
  loop_control:
    loop_var: cert_type

- name: etcd container
  docker_container:
    name: etcd
    image: gcr.io/etcd-development/etcd:v3.2.9
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ certs_path }}/:/certs/"
      - /var/lib/etcd/:/etcd-data/
    env:
      ETCDCTL_API: 3
      ETCDCTL_INSECURE_TRANSPORT: false
      ETCDCTL_CACERT: /certs/etcd-server-ca.crt
      ETCDCTL_CERT: /certs/etcd-client.crt
      ETCDCTL_KEY: /certs/etcd-client.key
      ETCDCTL_ENDPOINTS: |-
        {%- for host in groups['controllers'] -%}
        https://{{ hostvars[host]['ansible_fqdn'] }}:{{ client_port }}
        {%- if not loop.last -%},{%- endif -%}
        {%- endfor -%}
    entrypoint: etcd
    command: >
      --data-dir=/etcd-data
      --name={{ ansible_hostname }}
      --client-cert-auth
      --trusted-ca-file=/certs/etcd-client-ca.crt
      --cert-file=/certs/etcd-server.crt
      --key-file=/certs/etcd-server.key
      --peer-client-cert-auth
      --peer-trusted-ca-file=/certs/etcd-peer-ca.crt
      --peer-cert-file=/certs/etcd-peer.crt
      --peer-key-file=/certs/etcd-peer.key
      --initial-advertise-peer-urls=https://{{ ansible_fqdn }}:{{ peer_port }}
      --listen-peer-urls=https://{{ ansible_vlan10.ipv4.address }}:{{ peer_port }}
      --advertise-client-urls=https://{{ ansible_fqdn }}:{{ client_port }}
      --listen-client-urls=https://{{ ansible_vlan10.ipv4.address }}:{{ client_port }}
      --initial-cluster-state=new
      --initial-cluster-token={{ cluster_token }}
      --initial-cluster=
      {%- for host in groups['controllers'] -%}
      {{ host }}=https://{{ hostvars[host]['ansible_fqdn'] }}:{{ peer_port }}
      {%- if not loop.last -%},{%- endif -%}
      {%- endfor -%}
  vars:
    ansible_python_interpreter: /opt/ansible/bin/python
