---

- name: Update bootstrap-etcd {{ item }} {{ fact.key }} fact
  json_file:
    path: /etc/ansible/facts.d/certs.fact
    location: "{{ fact.location }}"
    key: "{{ fact.key }}"
    data: "{{ fact.data }}"
