---

- import_tasks: fetch_ca.yml

- name: Check if CAs match
  fail:
    msg: CAs do not match; please run roll_ca playbook
  when:
    - ca_bundle != []
    - new_ca_cert not in ca_bundle

- include_tasks: write_fact.yml
  loop_control:
    loop_var: fact
  with_items:
    - location: "{{ prefix }}{{ service }}-{{ ca_cert_type }}"
      key: ca
      data:
        - "{{ new_ca_cert }}"
  no_log: True
  when: ca_bundle == []
