---

- import_tasks: generate_certs.yml
  when: generate_certs

- name: Reload local facts
  setup:
    gather_subset: "!all,!min,local"

- name: Ensure {{ prefix }}{{ service }} certs directory exists
  file:
    state: directory
    path: /etc/certs/{{ prefix }}{{ service }}/

- name: Write {{ prefix }}{{ service }} {{ cert_type }} ca
  copy:
    dest: /etc/certs/{{ prefix }}{{ service }}/{{ cert_type }}_ca.crt
    content: "{{ ansible_local.certs['{}{}-{}'.format(prefix, service, cert_type)].ca }}"

- name: Write {{ prefix }}{{ service }} {{ cert_type }} cert
  copy:
    dest: /etc/certs/{{ prefix }}{{ service }}/{{ cert_type }}.crt
    content: "{{ ansible_local.certs['{}{}-{}'.format(prefix, service, cert_type)].crt }}"

- name: Write {{ prefix }}{{ service }} {{ cert_type }} key
  copy:
    dest: /etc/certs/{{ prefix }}{{ service }}/{{ cert_type }}.key
    content: "{{ ansible_local.certs['{}{}-{}'.format(prefix, service, cert_type)].key }}"
