---

- name: Ensure {{ prefix }}{{ service }} certs directory exists
  file:
    state: directory
    path: "{{ certs_path }}"

- name: Roll CA certifications
  include_tasks: roll_ca.yml
  when: roll_ca

- name: Ensure CA exist
  include_tasks: ca_cert.yml
  when:
    - not roll_ca
    - ca_cert_type is defined

- name: Ensure certs exist
  include_tasks: certs.yml
  when:
    - not roll_ca
    - ca_cert_type is not defined

- meta: flush_handlers

- name: Write {{ prefix }}{{ service }} {{ ca_cert_type | default(cert_type) }} ca
  copy:
    dest: "{{ certs_path }}/{{ service }}-{{ ca_cert_type }}-ca.crt"
    content: "{{ ''.join(ansible_local.certs['{}{}-{}'.format(prefix, service, ca_cert_type)].ca) }}"
  when: ca_cert_type is defined

- name: Write {{ prefix }}{{ service }} {{ ca_cert_type | default(cert_type) }} crt
  copy:
    dest: "{{ certs_path }}/{{ service }}-{{ cert_type }}.crt"
    content: "{{ ansible_local.certs['{}{}-{}'.format(prefix, service, cert_type)].crt }}"
  when:
    - not roll_ca
    - ca_cert_type is not defined

- name: Write {{ prefix }}{{ service }} {{ ca_cert_type | default(cert_type) }} key
  copy:
    dest: "{{ certs_path }}/{{ service }}-{{ cert_type }}.key"
    content: "{{ ansible_local.certs['{}{}-{}'.format(prefix, service, cert_type)].key }}"
  when:
    - not roll_ca
    - ca_cert_type is not defined
