---

- name: Ensure {{ prefix }}{{ service }} certs directory exists
  file:
    state: directory
    path: "{{ certs_path }}"

- name: Roll CA certifications
  include_tasks: roll_ca.yml
  when: roll_ca

- block:
    - name: Ensure CA exist
      include_tasks: ca_cert.yml
      when: ca_cert_type is defined

    - name: Ensure certs exist
      include_tasks: certs.yml
      when: ca_cert_type is not defined
  when: not roll_ca
