---

- import_tasks: fetch_ca.yml

- name: Combine ca bundle
  set_fact:
    final_ca_bundle: "{{ ca_bundle + [new_ca_cert] }}"
  when:
    - ca_bundle != []
    - new_ca_cert not in ca_bundle

- name: Retain ca bundle
  set_fact:
    final_ca_bundle: "{{ ca_bundle }}"
  when:
    - ca_bundle != []
    - new_ca_cert in ca_bundle
    - not remove_old_ca_certs

- name: Write single ca cert
  set_fact:
    final_ca_bundle:
      - "{{ new_ca_cert }}"
  when: (ca_bundle == []) or (new_ca_cert in ca_bundle and remove_old_ca_certs)

- include_tasks: write_fact.yml
  loop_control:
    loop_var: fact
  with_items:
    - location: "{{ prefix }}{{ service }}-{{ ca_cert_type }}"
      key: ca
      data: "{{ final_ca_bundle }}"
  no_log: True
