---

- import_tasks: fetch_ca.yml

- name: Combine ca certs
  set_fact:
    final_ca_cert: "{{ ca_cert }}{{ new_ca_cert }}"
  when: ca_cert != new_ca_cert

- name: Write single ca certs
  set_fact:
    final_ca_cert: "{{ new_ca_cert }}"
  when: ca_cert == new_ca_cert

- include_tasks: write_fact.yml
  loop_control:
    loop_var: fact
  with_items:
    - location: "{{ prefix }}{{ service }}-{{ ca_cert_type }}"
      key: ca
      data: "{{ final_ca_cert }}"

- name: Write {{ prefix }}{{ service }} {{ ca_cert_type }} ca
  copy:
    dest: "{{ certs_path }}/{{ service }}-{{ ca_cert_type }}-ca.crt"
    content: "{{ final_ca_cert }}"
  notify: Reload local facts
