---
- include_role:
    name: certs
  with_items:
    - client
    - server
  vars:
    service: vault
    delegate_host: "{{ groups['bootstrap_vault'][0] }}"
  loop_control:
    loop_var: ca_cert_type
  notify: Reload vault config

- include_role:
    name: certs
  with_items:
    - client
    - server
  vars:
    service: vault
    delegate_host: "{{ groups['bootstrap_vault'][0] }}"
  loop_control:
    loop_var: cert_type
  notify: Reload vault config

- include_role:
    name: certs
  with_items:
    - client
    - server
  vars:
    service: etcd
    prefix: vault-
    delegate_host: "{{ groups['bootstrap_vault'][0] }}"
  loop_control:
    loop_var: ca_cert_type
  notify: Reload vault config

- include_role:
    name: certs
  with_items:
    - client
  vars:
    service: etcd
    prefix: vault-
    delegate_host: "{{ groups['bootstrap_vault'][0] }}"
  loop_control:
    loop_var: cert_type
  notify: Reload vault config
