---
- include_role:
    name: certs
  with_items:
    - client
    - server
  vars:
    service: vault
    delegate_host: "{{ groups['bootstrap_vault'][0] }}"
  loop_control:
    loop_var: cert_type

- include_role:
    name: certs
  with_items:
    - client
  vars:
    service: etcd
    prefix: vault-
    delegate_host: "{{ groups['bootstrap_vault'][0] }}"
  loop_control:
    loop_var: cert_type

- name: Ensure vault config directory exists
  file:
    state: directory
    path: /etc/vault/

- name: Vault config
  copy:
    dest: /etc/vault/config.hcl
    content: |
        api_addr = "https://{{ ansible_fqdn }}:8200"
        storage "etcd" {
          address = "
            {%- for host in groups['controllers'] -%}
            https://{{ hostvars[host]['ansible_fqdn'] }}:2389
            {%- if not loop.last -%},{%- endif -%}
            {%- endfor -%}
          "
          ha_enabled = "true"
          #username = "{{ etcd_username | default('vault') }}"
          #password = "{{ etcd_password | default('password') }}"
          tls_ca_file = "/certs/etcd-server-ca.crt"
          tls_cert_file = "/certs/etcd-client.crt"
          tls_key_file = "/certs/etcd-client.key"
        }
        listener "tcp" {
          address = "{{ ansible_vlan10.ipv4.address }}:8200"
          tls_require_and_verify_client_cert = true
          tls_cert_file = "/certs/vault-server.crt"
          tls_key_file = "/certs/vault-server.key"
          tls_client_ca_file = "/certs/vault-client-ca.crt"
        }

- name: vault container
  docker_container:
    name: vault
    image: vault:0.9.0
    restart_policy: unless-stopped
    network_mode: host
    capabilities:
      - IPC_LOCK
    volumes:
      - "{{ certs_path }}/:/certs/"
      - /etc/vault/:/vault/config/
      - /var/lib/vault/:/vault/file/
      - /var/log/vault/:/vault/logs/
    env:
      VAULT_ADDR: https://{{ ansible_fqdn }}:8200
      VAULT_CACERT: /certs/vault-server-ca.crt
      VAULT_CLIENT_CERT: /certs/vault-client.crt
      VAULT_CLIENT_KEY: /certs/vault-client.key
    command: server
  vars:
    ansible_python_interpreter: /opt/ansible/bin/python
