---
- name: Check if docker venv exists
  stat:
    path: /opt/venv/docker
  register: venv

- include_tasks: setup_venv.yaml
  vars:
    venv_dest: /opt/venv/docker
  when: not venv.stat.exists

- name: Install packages
  pip:
    name:
      - docker-compose
      - pyopenssl
    virtualenv: /opt/venv/docker
